# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root, sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/fwAo+z/oX/8+g6XSQeFqFoJncXZoWhK8yfzvNi5wQA35LGJh6HchwlpuMe/WdSxkWwDvcJMsTonr89xZTsoF592ybPinADGjBbCngJFOQWzC19K9b3+dGYI977k0DqP4bTgKoYajBs+FIThIZ/0sJ2TenpMrK60EpPwW9g5o5KXx3l0qZ+RqYjliiY71lDQGKg56Oo6ddvXLEj/rJBmAZdpGbBOpa2UrHocLWxeZwrtJJUQ7iJbXCSB5fBvTB8LPKMl8yGQp0937Ua0Z4rMzM6MaKGsIhS/0f5wnASLEdZSc+sEWapCSivZyJ3oB20loWpKnCUQOI3TKP5F7yxwP15CFGDSFoTtCn+bwJKerkZSL7RK+5aaS/ZjiRO/anMjQZKuFqgmaWF3kJXokuLgH2fvWviCalfEjqQ5QhxVLajFDbfRe7fUFkGPbU1cqd2z2JXM2df3Fk9LtC7hM+0NShI/d4+QykQRhmJKiZ44U2YNtV1iDU3E9+q0EKtf2yvE= nfabredev@gmail.com

# Downloads the golang package
packages:
  - golang-go

# Sets the GOPATH & downloads the demo payload
runcmd:
  - sudo su terraform
  - sudo mkdir /home/terraform/go
  - sudo chown terraform:hashicorp /home/terraform/go
  - export GOPATH=/home/terraform/go
  - go get github.com/hashicorp/learn-go-webapp-demo
